### ISSUE TITLE
Best approach to adding new commands?

### ISSUE THREAD

**Issue by shilad** [dmlc/ps-lite#45]
In the v.1 version of ps-lite, the command inside a message was an int (hidden within protobuf). This made it easy to add new commands. The new version uses an enum for a command, so it doesn't seem to be extensible.

I'm trying to implement a distributed tracker (similar to the direction difacto is headed). However, it's not clear to me what the best was is to do this on top of a Message. Is the best approach handling the command exclusively within the Message payload (e.g. the vector of safe arrays)? Are there other ways to do this? Or should ps-lite not be used at all for this purpose?

Thanks for you advice!

**Comment by shilad** [comment]
I just noticed the `head` field in the Message. Maybe this is what the field is intended for?

**Comment by mli** [comment]
yeah, i used the int `head` and string `body` in a message for general purpose data communication. often `head` is for a command id, `body` for a command string or return results. body cannot be too large to exceed protobuf's size limit, i guess 64MB in default.

i dropped the name `command` since tianqi think it's strange...

**Comment by mli** [comment]
the tracker should be implemented by `SimpleApp` easily. I guess you don't need to look into `Message`

**Comment by shilad** [comment]
Thanks!
