### ISSUE TITLE
SArray is buggy

### ISSUE THREAD

**Issue by zhangyafeikimi** [dmlc/ps-lite#76]
#include "ps/sarray.h"

int main(int argc, char *argv[]) {
  ps::SArray<int> sa1{1, 2, 3, 4, 5, 6, 7, 8, 9};
  ps::SArray<int> sa2(sa1);

  sa1.pop_back();

  std::cout << sa1.size() << std::endl;
  std::cout << sa2.size() << std::endl;

  return 0;
}

outputs:
8
9

"sa1" and "sa2" should be the same, i think, by design.
But "size_" and "capacity_" are managed separately, it is a bug.

**Comment by BaiGang** [comment]
That's expected.

A shared array provides mechanism of managing the resources, i.e ownership
of the memory allocated, so that the underlying buffer won't be reallocated
when it's still processed by another "owner".

Also, if you want the properties be shared as well, a better way is to wrap
the object with a shared_ptr.

**Comment by zhangyafeikimi** [comment]
cool, i know it. i got the design.
